2019-10-05 12:57:25,484 : kivy : Factory: 194 symbols loaded
2019-10-05 12:57:25,600 : kivy : Image: Providers: img_tex, img_imageio, img_dds, img_sdl2, img_pil, img_gif (img_ffpyplayer ignored)
2019-10-05 12:57:25,656 : kivy : VideoGstplayer: Using Gstreamer 1.10.2.0
2019-10-05 12:57:25,656 : kivy : Video: Provider: gstplayer
2019-10-05 12:57:25,696 : kivy : Loading MPF-MC controller
2019-10-05 12:57:25,696 : mpfmc : Mission Pinball Framework Media Controller v0.52.5
2019-10-05 12:57:25,696 : mpfmc : Mission Pinball Framework Game Engine v0.52.7
2019-10-05 12:57:25,696 : mpfmc : Machine path: /Users/brianevans/Projects/HeistMPF
2019-10-05 12:57:25,697 : ConfigProcessor : Config file in cache changed: /Users/brianevans/Projects/HeistMPF/config/config
2019-10-05 12:57:25,697 : ConfigProcessor : Loading config from file /Users/brianevans/Projects/Heist2/lib/python3.6/site-packages/mpfmc/mcconfig.yaml.
2019-10-05 12:57:25,747 : ConfigProcessor : Loading config: /Users/brianevans/Projects/Heist2/lib/python3.6/site-packages/mpfmc/mcconfig.yaml
2019-10-05 12:57:25,761 : ConfigProcessor : Loading config from file /Users/brianevans/Projects/HeistMPF/config/config.
2019-10-05 12:57:25,789 : kivy : YAML error found in file /Users/brianevans/Projects/HeistMPF/config/config.yaml. Line 155,Position 21: mapping values are not allowed here
  in "/Users/brianevans/Projects/HeistMPF/config/config.yaml", line 155, column 21
Traceback (most recent call last):
  File "/Users/brianevans/Projects/Heist2/lib/python3.6/site-packages/mpf/file_interfaces/yaml_interface.py", line 198, in load
    config = self.process(f)
  File "/Users/brianevans/Projects/Heist2/lib/python3.6/site-packages/mpf/file_interfaces/yaml_interface.py", line 224, in process
    return yaml.load(data_string, Loader=MpfLoader)
  File "/Users/brianevans/Projects/Heist2/lib/python3.6/site-packages/ruamel/yaml/main.py", line 639, in load
    return loader._constructor.get_single_data()  # type: ignore
  File "/Users/brianevans/Projects/Heist2/lib/python3.6/site-packages/ruamel/yaml/constructor.py", line 102, in get_single_data
    node = self.composer.get_single_node()
  File "/Users/brianevans/Projects/Heist2/lib/python3.6/site-packages/ruamel/yaml/composer.py", line 75, in get_single_node
    document = self.compose_document()
  File "/Users/brianevans/Projects/Heist2/lib/python3.6/site-packages/ruamel/yaml/composer.py", line 96, in compose_document
    node = self.compose_node(None, None)
  File "/Users/brianevans/Projects/Heist2/lib/python3.6/site-packages/ruamel/yaml/composer.py", line 132, in compose_node
    node = self.compose_mapping_node(anchor)
  File "/Users/brianevans/Projects/Heist2/lib/python3.6/site-packages/ruamel/yaml/composer.py", line 194, in compose_mapping_node
    item_value = self.compose_node(node, item_key)
  File "/Users/brianevans/Projects/Heist2/lib/python3.6/site-packages/ruamel/yaml/composer.py", line 132, in compose_node
    node = self.compose_mapping_node(anchor)
  File "/Users/brianevans/Projects/Heist2/lib/python3.6/site-packages/ruamel/yaml/composer.py", line 194, in compose_mapping_node
    item_value = self.compose_node(node, item_key)
  File "/Users/brianevans/Projects/Heist2/lib/python3.6/site-packages/ruamel/yaml/composer.py", line 132, in compose_node
    node = self.compose_mapping_node(anchor)
  File "/Users/brianevans/Projects/Heist2/lib/python3.6/site-packages/ruamel/yaml/composer.py", line 194, in compose_mapping_node
    item_value = self.compose_node(node, item_key)
  File "/Users/brianevans/Projects/Heist2/lib/python3.6/site-packages/ruamel/yaml/composer.py", line 130, in compose_node
    node = self.compose_sequence_node(anchor)
  File "/Users/brianevans/Projects/Heist2/lib/python3.6/site-packages/ruamel/yaml/composer.py", line 163, in compose_sequence_node
    node.value.append(self.compose_node(node, index))
  File "/Users/brianevans/Projects/Heist2/lib/python3.6/site-packages/ruamel/yaml/composer.py", line 132, in compose_node
    node = self.compose_mapping_node(anchor)
  File "/Users/brianevans/Projects/Heist2/lib/python3.6/site-packages/ruamel/yaml/composer.py", line 187, in compose_mapping_node
    while not self.parser.check_event(MappingEndEvent):
  File "/Users/brianevans/Projects/Heist2/lib/python3.6/site-packages/ruamel/yaml/parser.py", line 144, in check_event
    self.current_event = self.state()
  File "/Users/brianevans/Projects/Heist2/lib/python3.6/site-packages/ruamel/yaml/parser.py", line 547, in parse_block_mapping_key
    if self.scanner.check_token(KeyToken):
  File "/Users/brianevans/Projects/Heist2/lib/python3.6/site-packages/ruamel/yaml/scanner.py", line 160, in check_token
    self.fetch_more_tokens()
  File "/Users/brianevans/Projects/Heist2/lib/python3.6/site-packages/ruamel/yaml/scanner.py", line 273, in fetch_more_tokens
    return self.fetch_value()
  File "/Users/brianevans/Projects/Heist2/lib/python3.6/site-packages/ruamel/yaml/scanner.py", line 626, in fetch_value
    self.reader.get_mark())
ruamel.yaml.scanner.ScannerError: mapping values are not allowed here
  in "/Users/brianevans/Projects/HeistMPF/config/config.yaml", line 155, column 21

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/brianevans/Projects/Heist2/lib/python3.6/site-packages/mpfmc/commands/mc.py", line 209, in __init__
    thread_stopper=thread_stopper).run()
  File "/Users/brianevans/Projects/Heist2/lib/python3.6/site-packages/mpfmc/core/mc.py", line 97, in __init__
    self.machine_config = self._load_config()
  File "/Users/brianevans/Projects/Heist2/lib/python3.6/site-packages/mpfmc/core/mc.py", line 223, in _load_config
    mpf_config = self.mpf_config_processor.load_config_files_with_cache(files, "machine", True)
  File "/Users/brianevans/Projects/Heist2/lib/python3.6/site-packages/mpf/core/config_processor.py", line 112, in load_config_files_with_cache
    ignore_unknown_sections)
  File "/Users/brianevans/Projects/Heist2/lib/python3.6/site-packages/mpf/core/config_processor.py", line 132, in _load_config_file_and_return_loaded_files
    config = FileManager.load(filename, expected_version_str, True)
  File "/Users/brianevans/Projects/Heist2/lib/python3.6/site-packages/mpf/core/file_manager.py", line 99, in load
    return interface.load(file, verify_version, halt_on_error)
  File "/Users/brianevans/Projects/Heist2/lib/python3.6/site-packages/mpf/file_interfaces/yaml_interface.py", line 205, in load
    raise ValueError(msg)
ValueError: YAML error found in file /Users/brianevans/Projects/HeistMPF/config/config.yaml. Line 155,Position 21: mapping values are not allowed here
  in "/Users/brianevans/Projects/HeistMPF/config/config.yaml", line 155, column 21
2019-10-05 12:57:25,790 : kivy : Stopping child threads... (0 remaining)
2019-10-05 12:57:25,791 : kivy : All child threads stopped.
